spring.application.name=quickjob

#config database
###
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/quickjob
spring.datasource.username=root
spring.datasource.password=118118
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
###

#config jwt
###
thinher.jwt.base64-secret=6YIgpBoPrHadlNsyMJBRSMt5LimTL0Lkc3hjlJaDis1fcHcu+YqRH3VD41xupqmOV7+RR4glTH6MwInnx3nx3w==
#expiration: 1 day (24h * 60m * 60s = 86400s)
thinher.jwt.token-validity-in-seconds=8640000
###

#config upload file
###
# #default = 1MB
# spring.servlet.multipart.max-file-size=50MB  

# #default = 10 MB (form data)
# spring.servlet.multipart.max-request-size=50MB
###

